### ISSUE TITLE
Unable to get useful error information from CreateSendException

### ISSUE THREAD

**Issue by ammojamo** [campaignmonitor/createsend-java#51]
If an error occurs during a request (e.g. calling `Subscribers.addMany` in my case) a `CreateSendException` is thrown with a message that says:

> The CreateSend API responded with the following client error 210: Subscriber Import had some failures. Check resultData for more details

But there are no other properties on the exception object, so no way to actually check "resultData" for more details.

**Comment by tobio** [comment]
You're probably getting a [`BadRequestException`](https://github.com/campaignmonitor/createsend-java/blob/master/src/com/createsend/util/exceptions/BadRequestException.java) in that case.

**Comment by ammojamo** [comment]
Thanks - you are right, it makes sense now! Please excuse the false alarm :-)
